### ISSUE TITLE
Introduce feature `cmd` to build the CLI

### ISSUE THREAD

**Issue by clearloop** [gear-tech/gear-program#40]
### File Location(s)

https://github.com/gear-tech/gear-program/tree/master/src/cmd

### Proposal

Since we have requirements for using this project for writing tests, we can trim the `cmd` folder if users just want to use the library of this project

```toml
[features]
default = [ "cmd" ]
cmd = []
node-key = []
```

for using this library

```toml
gear-program = { version = "0.1.2", default-featulres = false }
```
